### ISSUE TITLE
SyntaxError in logs when opening URL

### ISSUE THREAD

**Issue by davidrustingha** [cnorick/ha-auto-guest-login#13]
When running the docker compose all is fine, when starting the container too.

When I go to the correct URL I see the redirecting screen but nothing happens. When I check the log afterwards it gives me this error

```
SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at Response.json (file:///app/node_modules/node-fetch/src/body.js:147:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getFlowId (file:///app/server.js:31:11)
    at async getCode (file:///app/server.js:35:18)
    at async getRedirectUri (file:///app/server.js:61:14)
    at async file:///app/server.js:73:12
Example app listening at http://localhost:80
```

Config:
```
version: "3"
services:
  ha-auto-guest-login:
    image: norick/ha-auto-guest-login:main
    container_name: ha-auto-guest-login
    environment:
      - CLIENTID=http://192.168.2.160:8123/
      - URL=http://192.168.2.160:8123/
      - DASH=lovelace-guest/lights (have also tried without the '/lights')
      - USER=guest-user
      - PASS=(password contains lowercase, uppercase, numbers and punctuation marks, might that be a problem?)
    ports:
      - 80:80
    restart: unless-stopped
```
